/*
 * BatteryManagement.h
 *
 *  Created on: 17 Feb 2023
 *      Author: Szymon Grzegorzewski
 */

#ifndef LIBRARIES_POWERMANAGEMENT_BATTERYMANAGEMENT_H_
#define LIBRARIES_POWERMANAGEMENT_BATTERYMANAGEMENT_H_


// PA15
#define MOSFETS_OFF  GPIOA->BSRR = 1<<31
#define MOSFETS_ON   GPIOA->BSRR = 1<<15


#endif /* LIBRARIES_POWERMANAGEMENT_BATTERYMANAGEMENT_H_ */
